$env:DATABASE_URL='postgres://app:app@127.0.0.1:5432/azums'
$env:STATUS_API_BIND='127.0.0.1:8082'
$env:STATUS_API_BEARER_TOKEN='dev-status-token'
$env:STATUS_API_REQUIRE_BEARER_AUTH='true'
$env:STATUS_API_PRINCIPAL_ROLE_BINDINGS='demo-operator=admin'
$env:STATUS_API_REQUIRE_PRINCIPAL_ROLE_BINDING='true'
$env:STATUS_API_PRINCIPAL_TENANT_BINDINGS='demo-operator=tenant_demo'
$env:STATUS_API_REQUIRE_PRINCIPAL_TENANT_BINDING='true'
$env:STATUS_API_REDACT_FAILURE_PROVIDER_DETAILS_FOR_VIEWER='true'
$env:STATUS_API_REDACT_CALLBACK_ERROR_DETAILS_FOR_VIEWER='true'
$env:STATUS_API_ENABLE_REPLAY='true'
$env:STATUS_API_REPLAY_DB_MAX_CONNECTIONS='4'
$env:STATUS_API_INTENT_ROUTES='solana.transfer.v1=adapter_solana;solana.broadcast.v1=adapter_solana'
$env:STATUS_API_ALLOWED_ADAPTERS='adapter_solana'
$env:EXECUTION_DISPATCH_QUEUE='execution.dispatch'
$env:EXECUTION_CALLBACK_QUEUE='execution.callback'
cargo run --manifest-path crates/status_api/Cargo.toml
