$env:DATABASE_URL='postgres://app:app@127.0.0.1:5432/azums'
$env:INGRESS_API_BIND='127.0.0.1:8081'
$env:INGRESS_BEARER_TOKEN='dev-ingress-token'
$env:INGRESS_PRINCIPAL_SUBMITTER_BINDINGS='ingress-service=internal_service'
$env:INGRESS_REQUIRE_PRINCIPAL_SUBMITTER_BINDING='true'
$env:INGRESS_PRINCIPAL_TENANT_BINDINGS='ingress-service=tenant_demo'
$env:INGRESS_REQUIRE_PRINCIPAL_TENANT_BINDING='true'
$env:INGRESS_REQUIRE_PRINCIPAL_ID='true'
$env:INGRESS_REQUIRE_SUBMITTER_KIND='true'
$env:INGRESS_REQUIRE_API_KEY_FOR_API_KEY_HOLDER='true'
$env:INGRESS_API_ALLOWED_SUBMITTERS='api_key_holder,internal_service,wallet_backend'
$env:INGRESS_WEBHOOK_ALLOWED_SUBMITTERS='signed_webhook_sender,internal_service'
$env:INGRESS_INTENT_ROUTES='solana.transfer.v1=adapter_solana;solana.broadcast.v1=adapter_solana'
$env:INGRESS_INTENT_SCHEMAS='solana.transfer.v1=solana.transfer.v1;solana.broadcast.v1=solana.broadcast.v1'
$env:INGRESS_REQUIRE_SCHEMA_FOR_ALL_ROUTES='true'
$env:EXECUTION_DISPATCH_QUEUE='execution.dispatch'
$env:EXECUTION_CALLBACK_QUEUE='execution.callback'
cargo run --manifest-path apps/ingress_api/Cargo.toml
