[package]
name = "azums-dashboard"
version = "0.1.3"
edition = "2021"
rust-version = "1.75"
description = "Web administration UI dashboard console for azums background job processing"
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlockForge-Dev/azums"
publish = false

[dependencies]
azums-core = { version = "0.1.3", path = "../azums-core" }
azums = { version = "0.1.3", path = "../azums" }
azums-postgres = { version = "0.1.3", path = "../azums-postgres" }
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "uuid", "chrono", "json"] }
anyhow = "1"
