[package]
name = "postgresflow-actix"
version = "0.2.0"
edition = "2021"
rust-version = "1.75"
description = "Native Actix Web extractor and background jobs integration for postgresflow"
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlockForge-Dev/postgresflow"
documentation = "https://docs.rs/postgresflow-actix"
homepage = "https://github.com/BlockForge-Dev/postgresflow"
readme = "../../README.md"
keywords = ["actix", "actix-web", "job-queue", "background-jobs", "extractor"]
categories = ["web-programming::HTTP-server", "asynchronous"]

[dependencies]
postgresflow = { path = "../postgresflow" }
postgresflow-core = { path = "../postgresflow-core" }

actix-web = "4"
futures-util = "0.3"

tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
anyhow = "1"
