[book]
authors = ["Azums Core Team"]
language = "en"
src = "src"
title = "Azums Guide & Reference"

[output.html]
git-repository-url = "https://github.com/BlockForge-Dev/azums"
edit-url-template = "https://github.com/BlockForge-Dev/azums/edit/main/docs/{path}"
site-url = "/azums/"
mathjax-support = false
default-theme = "navy"

[output.html.fold]
enable = true
level = 0
