name: Release Automation

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish Crates to Crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish postgresflow-core
        run: cargo publish -p postgresflow-core

      - name: Publish postgresflow-postgres
        run: cargo publish -p postgresflow-postgres

      - name: Publish postgresflow
        run: cargo publish -p postgresflow

      - name: Publish postgresflow-axum
        run: cargo publish -p postgresflow-axum

      - name: Publish postgresflow-actix
        run: cargo publish -p postgresflow-actix

      - name: Publish postgresflow-poem
        run: cargo publish -p postgresflow-poem

      - name: Publish postgresflow-rocket
        run: cargo publish -p postgresflow-rocket

      - name: Publish worker
        run: cargo publish -p worker
